#!/usr/bin/env python
import sys

cyanboot_path, boot_path = sys.argv[1:]
cyanboot_data = open(cyanboot_path, 'rb').read()
offset = 1024*512 - len(cyanboot_data)
boot_data = open(boot_path,'rb').read()
open(boot_path,'wb').write(cyanboot_data+'\x00'*offset+boot_data)