#!/usr/bin/env python
import sys

ramdisk_path, kernel_path = sys.argv[1:]
data = '\x00'*288
ramdisk_data = data + open(ramdisk_path,'rb').read()
if ramdisk_data.startswith('\x1F\x8B\x08'):
    ramdisk_data = ramdisk_data+data
else:
    print 'WARNING: ramdisk already patched, skipping...'
open(ramdisk_path,'wb').write(ramdisk_data)
kernel_data = data + open(kernel_path,'rb').read()
if kernel_data.startswith('\x00\x00\xA0'):
    kernel_data = data+kernel_data
else:
    print 'WARNING: kernel already patched, skipping...'
open(kernel_path,'wb').write(kernel_data)